source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

target 'DHPasscodeManagerExample' do
pod 'DHPasscodeManager', :git => 'https://github.com/donholly/DHPasscodeManager'
end

target 'DHPasscodeManagerTests' do

end

post_install do |installer|
  installer.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
      config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [ '$(PLATFORM_DIR)/Developer/Library/Frameworks' ]
    end
  end
end