source 'https://github.com/CocoaPods/Specs.git'

deployment_target = '8.0'

platform :ios, deployment_target 

target 'DHPasscodeManagerExample' do
pod 'DHPasscodeManager', :path => '../'
#pod 'DHPasscodeManager', :git => 'https://github.com/donholly/DHPasscodeManager'
end

target 'DHPasscodeManagerTests' do

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
		config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
